#Documento criado apartir do kubectl create secret tls <secret-name> --cert <certificate-pem-file> --key <private-key-pem-file> .
apiVersion: v1
kind: apiVersion: v1
kind: Secret
metadata: 
  creationTimestamp: null
  name: mysecret
type: kubernetes.io/tls
data:
  tls.crt: <base64 encoded certificate>
  tls.key: <base64 encoded private key >
