apiVersion: apps/v1
kind: Deployment
metadata:
  name: bandcoot-prod
  labels:
    app: bandcoot-prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bandcoot
  template:
    metadata:
      labels:
        app: bandcoot
        env: prod
        ver: "2"
    spec:
      containers:
      - image: gcr.io/kuar-demo/kuard-amd64:green
        name: kuard-amd64
        ports:
        - containerPort: 8080
